# Generated by Django 5.1.4 on 2025-01-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_verificationtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
