# Generated by Django 5.1.4 on 2025-01-09 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_management', '0008_alter_agent_options_remove_agent_assigned_leads'),
        ('users', '0007_alter_customuser_profile_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='agency_management.agency'),
        ),
    ]
