# Generated by Django 5.1.4 on 2024-12-27 18:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('potential', models.CharField(choices=[('Cold', 'Cold Lead'), ('Luke Warm', 'Luke Warm Lead'), ('Hot', 'Hot Lead')], default='Cold', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('New Submission', 'New Submission'), ('Unsuccessful', 'Unsuccessful'), ('Pending Mandate', 'Pending Mandate'), ('Already Listed', 'Already Listed'), ('Listed', 'Listed'), ('Sold', 'Sold'), ('Commission Paid', 'Spotter Commission Paid'), ('Owner Not Found', 'Owner Not Found'), ('Other Sole Mandate', 'Other Sole Mandate')], default='New Submission', max_length=30)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lead', to='properties.property')),
                ('spotter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='users.customuser')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
