# Generated by Django 5.1.4 on 2025-01-02 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_management', '0008_alter_agent_options_remove_agent_assigned_leads'),
        ('leads', '0002_lead_assigned_agency_lead_assigned_agent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='assigned_agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to='agency_management.agency'),
        ),
    ]
