# Generated by Django 5.1.5 on 2025-03-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0003_alter_lead_assigned_agency"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="property_listing_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
