# Generated by Django 5.1.4 on 2024-12-27 19:04

import django.db.models.deletion
import django.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_management', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='id',
            field=models.UUIDField(default=django.db.models.fields.UUIDField, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='agency',
            name='principal_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agency_principal', to='users.customuser'),
        ),
    ]
