# Generated by Django 5.1.4 on 2025-01-02 12:09

import agency_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency_management', '0006_alter_agency_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=agency_management.models.generate_secure_filename),
        ),
        migrations.AddField(
            model_name='agency',
            name='logo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
