# Generated by Django 5.1.4 on 2025-01-02 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency_management', '0007_agency_logo_agency_logo_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='agent',
            name='assigned_leads',
        ),
    ]
